

ALL_SRC_FILE =AnimationElement.cpp \
Common.cpp \
ElementBase.cpp \
Fbx6ClassTemplateMap.cpp \
FbxAMatrix.cpp \
FbxAccumulatorEntry.cpp \
FbxAddBOF.cpp \
FbxAnimCurve.cpp \
FbxAnimCurveBase.cpp \
FbxAnimCurveDef.cpp \
FbxAnimCurveFilter.cpp \
FbxAnimCurveFilterConstantKeyReducer.cpp \
FbxAnimCurveFilterGimbleKiller.cpp \
FbxAnimCurveFilterKeyReducer.cpp \
FbxAnimCurveFilterKeySync.cpp \
FbxAnimCurveFilterMatrixConverter.cpp \
FbxAnimCurveFilterResample.cpp \
FbxAnimCurveFilterScale.cpp \
FbxAnimCurveFilterScaleByCurve.cpp \
FbxAnimCurveFilterScaleCompensate.cpp \
FbxAnimCurveFilterTSS.cpp \
FbxAnimCurveFilterUnroll.cpp \
FbxAnimCurveKey.cpp \
FbxAnimCurveKeyBase.cpp \
FbxAnimCurveKey_Impl.cpp \
FbxAnimCurveNode.cpp \
FbxAnimEvalState.cpp \
FbxAnimEvaluator.cpp \
FbxAnimLayer.cpp \
FbxAnimStack.cpp \
FbxAnimUtilities.cpp \
FbxArray.cpp \
FbxArrayBool.cpp \
FbxArrayDouble.cpp \
FbxArrayInt.cpp \
FbxArrayLong.cpp \
FbxArrayVector2.cpp \
FbxArrayVector4.cpp \
FbxAssignBOF.cpp \
FbxAtomOp.cpp \
FbxAxisSystem.cpp \
FbxBase64Decoder.cpp \
FbxBase64Encoder.cpp \
FbxBaseAllocator.cpp \
FbxBindingOperator.cpp \
FbxBindingTable.cpp \
FbxBindingTableBase.cpp \
FbxBindingTableEntry.cpp \
FbxBindingsEntryView.cpp \
FbxBitSet.cpp \
FbxBlendShape.cpp \
FbxBlendShapeChannel.cpp \
FbxBlob.cpp \
FbxBoundary.cpp \
FbxCache.cpp \
FbxCachedEffect.cpp \
FbxCamera.cpp \
FbxCameraManipulator.cpp \
FbxCameraStereo.cpp \
FbxCameraSwitcher.cpp \
FbxCharCompare.cpp \
FbxCharPtrSet.cpp \
FbxCharacter.cpp \
FbxCharacterLink.cpp \
FbxCharacterPose.cpp \
FbxCharacterPropertyInfo.cpp \
FbxClassId.cpp \
FbxCloneManager.cpp \
FbxCluster.cpp \
FbxCollection.cpp \
FbxCollectionExclusive.cpp \
FbxColor.cpp \
FbxConditionalBOF.cpp \
FbxConnection.cpp \
FbxConnectionPoint.cpp \
FbxConnectionPointFilter.cpp \
FbxConstantEntryView.cpp \
FbxConstraint.cpp \
FbxConstraintAim.cpp \
FbxConstraintParent.cpp \
FbxConstraintPosition.cpp \
FbxConstraintRotation.cpp \
FbxConstraintScale.cpp \
FbxConstraintSingleChainIK.cpp \
FbxConstraintUtils.cpp \
FbxContainer.cpp \
FbxContainerTemplate.cpp \
FbxControlSet.cpp \
FbxControlSetLink.cpp \
FbxControlSetPlug.cpp \
FbxCriteria.cpp \
FbxDataType.cpp \
FbxDateTime.cpp \
FbxDeformationsEvaluator.cpp \
FbxDeformer.cpp \
FbxDegreeToRadianBOF.cpp \
FbxDisplayLayer.cpp \
FbxDistance.cpp \
FbxDocument.cpp \
FbxDocumentInfo.cpp \
FbxDouble3.cpp \
FbxDouble4.cpp \
FbxDualQuaternion.cpp \
FbxEffector.cpp \
FbxEmbeddedFilesAccumulator.cpp \
FbxEmitter.cpp \
FbxEntryView.cpp \
FbxEuler.cpp \
FbxEvalState.cpp \
FbxEventBase.cpp \
FbxEventHandler.cpp \
FbxEventPostExport.cpp \
FbxEventPostImport.cpp \
FbxEventPreExport.cpp \
FbxEventPreImport.cpp \
FbxEventReferencedDocument.cpp \
FbxExporter.cpp \
FbxExternalDocRefListener.cpp \
FbxFile.cpp \
FbxFileTexture.cpp \
FbxFileUtils.cpp \
FbxFolder.cpp \
FbxGate.cpp \
FbxGeometry.cpp \
FbxGeometryBase.cpp \
FbxGeometryConverter.cpp \
FbxGeometryWeightedMap.cpp \
FbxGlobalCameraSettings.cpp \
FbxGlobalLightSettings.cpp \
FbxGlobalSettings.cpp \
FbxGobo.cpp \
FbxHalfFloat.cpp \
FbxHungryAllocator.cpp \
FbxIO.cpp \
FbxIOBase.cpp \
FbxIODefaultRenderResolution.cpp \
FbxIOFileHeaderInfo.cpp \
FbxIOPluginRegistry.cpp \
FbxIOSettings.cpp \
FbxImplementation.cpp \
FbxImplementationFilter.cpp \
FbxImporter.cpp \
FbxIsYupBOF.cpp \
FbxIteratorDstBase.cpp \
FbxIteratorSrcBase.cpp \
FbxJnimgr.cpp \
FbxLODGroup.cpp \
FbxLayer.cpp \
FbxLayerContainer.cpp \
FbxLayerElement.cpp \
FbxLayerElementArray.cpp \
FbxLayerElementArrayTemplate.cpp \
FbxLayerElementArrayTemplateBool.cpp \
FbxLayerElementArrayTemplateDouble.cpp \
FbxLayerElementArrayTemplateInt.cpp \
FbxLayerElementArrayTemplateVector2.cpp \
FbxLayerElementArrayTemplateVector4.cpp \
FbxLayerElementBinormal.cpp \
FbxLayerElementCrease.cpp \
FbxLayerElementHole.cpp \
FbxLayerElementMaterial.cpp \
FbxLayerElementNormal.cpp \
FbxLayerElementPolygonGroup.cpp \
FbxLayerElementSmoothing.cpp \
FbxLayerElementTangent.cpp \
FbxLayerElementTexture.cpp \
FbxLayerElementUV.cpp \
FbxLayerElementUserData.cpp \
FbxLayerElementVertexColor.cpp \
FbxLayerElementVisibility.cpp \
FbxLayerEntryView.cpp \
FbxLayeredTexture.cpp \
FbxLibrary.cpp \
FbxLight.cpp \
FbxLimits.cpp \
FbxLimitsUtilities.cpp \
FbxLine.cpp \
FbxListener.cpp \
FbxLoadingStrategy.cpp \
FbxLocalTime.cpp \
FbxManager.cpp \
FbxMarker.cpp \
FbxMaterialConverter.cpp \
FbxMatrix.cpp \
FbxMemoryPool.cpp \
FbxMesh.cpp \
FbxMultiplyBOF.cpp \
FbxMultiplyDistBOF.cpp \
FbxMutex.cpp \
FbxNameFilter.cpp \
FbxNameHandler.cpp \
FbxNameMapCompare.cpp \
FbxNode.cpp \
FbxNodeAttribute.cpp \
FbxNodeDirectionBOF.cpp \
FbxNodeEvalState.cpp \
FbxNodePositionBOF.cpp \
FbxNull.cpp \
FbxNurbs.cpp \
FbxNurbsCurve.cpp \
FbxNurbsSurface.cpp \
FbxObject.cpp \
FbxObjectFilter.cpp \
FbxObjectStringMap.cpp \
FbxObjectsContainer.cpp \
FbxOneOverXBOF.cpp \
FbxOperatorEntryView.cpp \
FbxOpticalReference.cpp \
FbxPatch.cpp \
FbxPathUtils.cpp \
FbxPeripheral.cpp \
FbxPlugin.cpp \
FbxPluginContainer.cpp \
FbxPose.cpp \
FbxPowerBOF.cpp \
FbxProceduralTexture.cpp \
FbxProcessor.cpp \
FbxProcessorShaderDependency.cpp \
FbxProcessorXRefCopy.cpp \
FbxProcessorXRefCopyUserLibrary.cpp \
FbxProgress.cpp \
FbxProperty.cpp \
FbxPropertyAttr.cpp \
FbxPropertyConnect.cpp \
FbxPropertyEntry.cpp \
FbxPropertyEntryView.cpp \
FbxPropertyEvalState.cpp \
FbxPropertyHandle.cpp \
FbxPropertyIdGenerator.cpp \
FbxPropertyInfo.cpp \
FbxPropertyPage.cpp \
FbxPropertyTBool.cpp \
FbxPropertyTDouble.cpp \
FbxPropertyTFbxDouble3.cpp \
FbxPropertyTFbxReference.cpp \
FbxPropertyTInt.cpp \
FbxQuaternion.cpp \
FbxQuery.cpp \
FbxReader.cpp \
FbxReaderCollada.cpp \
FbxReaderFbx5.cpp \
FbxReaderFbx6.cpp \
FbxReaderFbx7.cpp \
FbxRenamingStrategy.cpp \
FbxRenamingStrategyBase.cpp \
FbxRenamingStrategyFbx5.cpp \
FbxRenamingStrategyFbx6.cpp \
FbxRenamingStrategyFbx7.cpp \
FbxRenamingStrategyInterface.cpp \
FbxRenamingStrategyNumber.cpp \
FbxRenamingStrategyUtils.cpp \
FbxRootNodeUtility.cpp \
FbxRotationOrder.cpp \
FbxScene.cpp \
FbxSceneReference.cpp \
FbxSceneRenamer.cpp \
FbxScopedLoadingDirectory.cpp \
FbxScopedLoadingFileName.cpp \
FbxSelectionNode.cpp \
FbxSelectionSet.cpp \
FbxSemanticEntryView.cpp \
FbxSemaphore.cpp \
FbxSet.cpp \
FbxShape.cpp \
FbxSkeleton.cpp \
FbxSkin.cpp \
FbxSphericalToCartesianBOF.cpp \
FbxSpinLock.cpp \
FbxSpotDistributionChooserBOF.cpp \
FbxStatistics.cpp \
FbxStatus.cpp \
FbxStatusGlobal.cpp \
FbxStream.cpp \
FbxString.cpp \
FbxStringCompare.cpp \
FbxStringList.cpp \
FbxStringListItem.cpp \
FbxStringSymbol.cpp \
FbxSubDeformer.cpp \
FbxSubstractBOF.cpp \
FbxSurfaceLambert.cpp \
FbxSurfaceMaterial.cpp \
FbxSurfacePhong.cpp \
FbxSwitchBOF.cpp \
FbxSymbol.cpp \
FbxSymbolIDBOF.cpp \
FbxSyncStack.cpp \
FbxSystemUnit.cpp \
FbxTRSToMatrixBOF.cpp \
FbxTakeInfo.cpp \
FbxTexture.cpp \
FbxThread.cpp \
FbxThumbnail.cpp \
FbxTime.cpp \
FbxTimeSpan.cpp \
FbxTransform.cpp \
FbxTrimNurbsSurface.cpp \
FbxUserNotification.cpp \
FbxUserNotificationFilteredIterator.cpp \
FbxVector2.cpp \
FbxVector4.cpp \
FbxVectorDegreeToVectorRadianBOF.cpp \
FbxVertexCacheDeformer.cpp \
FbxVideo.cpp \
FbxWeightedMapping.cpp \
FbxWriter.cpp \
FbxWriterCollada.cpp \
FbxWriterFbx5.cpp \
FbxWriterFbx6.cpp \
FbxWriterFbx7.cpp \
FbxXRefManager.cpp \
HIK2FbxCharacterPropertyBridge.cpp \
LockAccessStatus.cpp \
XmlNodeDeletionPolicy.cpp 


OUTDIR = .\objs


all: $(OUTDIR) $(OUTDIR)/FbxsdkJNI.dll

installx86:  all
        copy /Y $(OUTDIR)\FbxsdkJNI.dll ..\..\Assets\Plugins\x86

installx64:  all
    copy /Y $(OUTDIR)\FbxsdkJNI.dll ..\..\Assets\Plugins\x86_64

$(OUTDIR) :
 if not exist "$(OUTDIR)" mkdir $(OUTDIR)

clean:
       if exist $(OUTDIR) del $(OUTDIR)\*

CFLAGS=-c -I"C:\Program Files\Java\jdk1.8.0_121\include" -I"C:\Program Files\Java\jdk1.8.0_121\include\win32" -I"C:\Program Files\Autodesk\FBX\FBX SDK\2015.1\include" 
LDFLAGS="C:\Program Files\Autodesk\FBX\FBX SDK\2015.1\lib\vs2013\x64\debug\libfbxsdk.lib"

all_obj: $(ALL_SRC_FILE)
          cl  $(CFLAGS) -DWIN32   /EHsc /Fo"$(OUTDIR)\\" /Fd"$(OUTDIR)\\" $(ALL_SRC_FILE)

# link
$(OUTDIR)/FbxsdkJNI.dll: all_obj
    link /NOLOGO /DLL /out:$(OUTDIR)/FbxsdkJNI.dll  $(OUTDIR)\*.obj $(LDFLAGS)